[package]
name = "numpy-100"
version = "0.1.0"
authors = ["Francesco Terenzi <fra.terenz1993@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.15.0", features = ["approx"] }
